from rply import LexerGenerator

lg = LexerGenerator()
lg.ignore(r"\s+")
lg.add("IF", r"if")
lg.add("WHILE", r"while")
lg.add("ELSE", r"else")
lg.add("PRINT", r'print')
lg.add("LPAREN", r"\(")
lg.add("RPAREN", r"\)")
lg.add("LBRACE", r"\{")
lg.add("RBRACE", r"\}")
lg.add("EQUAL", r"=")
lg.add("GREATER_EQUAL", r">=")
lg.add("GREATER", r">")
lg.add("LESS", r"<")
lg.add("LESS_EQUAL", r">=")
lg.add("SEMICOLON", r';')
lg.add("NUMBER", r"\d+")
lg.add("NAME", r"[A-Za-z_][a-zA-Z0-9_]*")
lg.add("CALL", r"call")
lg.add("READ", r"read")
lg.add("PLUS", r"\+")
lg.add("MINUS", r"-")
lg.add("DIV", "/")
lg.add("MUL", "\*")
lexer = lg.build()
